### ISSUE TITLE
rust_2018_idioms: build warning "hidden lifetime parameters in types are deprecated"

### ISSUE THREAD

**Issue by oherrala** [stepancheg/rust-protobuf#588] opened 2021-12-15 08:49 UTC
I get the following warnings when compiling my code (with 2.25.2):

```
303 |     fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected named lifetime parameter
    |
    = note: `-W elided-lifetimes-in-paths` implied by `-W rust-2018-idioms`
help: consider using the `'_` lifetime
    |
303 |     fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef<'_> {
```

Same kind of issue is previously reported in #435.

**Comment by stepancheg** [comment] 2022-02-08 00:52
Where is this code located?

**Comment by oherrala** [comment] 2022-02-08 06:56
This is the generated code:

```rust
impl ::protobuf::reflect::ProtobufValue for CollectorMessages {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}
```

`CollectorMessages` is defined in protobuf as:

```protobuf
message CollectorMessages {
    oneof message {
        SendObservationRequest send_observation_req = 1;
        SendObservationResponse send_observation_resp = 2;
    }
}
```

**Comment by stepancheg** [comment] 2022-02-08 16:28
Did you turn on `#[warn(rust_2018_idioms)]` explicitly?

Because otherwise I [cannot reproduce it](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b7de9f71f713618945d917862375f7bc).

**Comment by oherrala** [comment] 2022-02-08 21:01
Yes, apparently so. I just tried turning it on to see the warnings and off to not see them. Sorry I forgot to specify what lints I had turned on (I have quite a few).

```
export RUSTFLAGS="-W deprecated-in-future -W noop-method-call -W future-incompatible -W nonstandard-style -W rust-2018-compatibility -W rust-2018-idioms -W rust-2021-compatibility -W unused ${RUSTFLAGS}"
```

**Comment by stepancheg** [comment] 2022-02-08 21:11
If `#[warn(rust_2018_idioms)]` was inserted in generated code, would it be enough?

**Comment by oherrala** [comment] 2022-02-09 06:28
I think the generated code should be modified as described by the linter:

```rust
  impl ::protobuf::reflect::ProtobufValue for CollectorMessages {
-     fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
+     fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef<'_> {
          ::protobuf::reflect::ReflectValueRef::Message(self)
      }
  }
}```

**Comment by stepancheg** [comment] 2022-02-09 06:30
Yes, I think you are right, it would be safer this way.

**Comment by stepancheg** [comment] 2022-02-09 06:46
Interesting, current version from master does not have this warning (it generate similar code differently).

rust-protobuf v3 will be released in the following weeks. Is it critical to have this warning fixed in rust-protobuf v2?

**Comment by oherrala** [comment] 2022-02-09 07:27
No, it's not critical. Just annoying.

**Closed** 2022-02-20 05:23 UTC
