### ISSUE TITLE
trait objects without an explicit `dyn` are deprecated

### ISSUE THREAD

**Issue by xiaokang5350** [stepancheg/rust-protobuf#414] opened 2019-06-03 04:00 UTC
I use rustc 1.37.0-nightly and report  trait objects without an explicit `dyn` are deprecated warnings

**Comment by stepancheg** [comment] 2019-06-03 14:42
Yep, most error were fixed in https://github.com/stepancheg/rust-protobuf/commit/d6f783e4963f4de663d09db6e5ab4420736ba4ee and version 2.6.2, and more muted warnings are needed.

Note that rust-protobuf 2.6 cannot switch to `dyn` properly because of compatibility with Rust 1.26.

Probably rust-protobuf 2.7 needs to require Rust 1.27 where `dyn` is stable.

**Comment by stepancheg** [comment] 2019-06-08 22:07
rust-protobuf 2.7 (unreleased branch) now works only with Rust 1.27.

**Comment by rtsisyk** [comment] 2019-06-24 05:12
Any plans to release 2.7?

**Comment by stepancheg** [comment] 2019-06-24 12:35
In about a week. I'm a bit worried that something may break, so if someone wants to help with code review, I'd appreciate that. ([Changelog](https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md))

**Comment by stepancheg** [comment] 2019-07-01 23:39
2.7 is released.

**Comment by jakubadamw** [comment] 2019-07-10 15:34
@stepancheg, well, it's released, but the code that gets generated still produces ``trait objects without an explicit `dyn` are deprecated`` warnings under Rust >= 1.27. Shouldn't this issue be reopened, then?

I presume that the minimal Rust version required by `protoc-rust` should go hand in hand with the minimal version the generated code is expected to compile under, correct? Therefore, if the version 2.7 requires Rust 1.27, so should the code it generates, and thereby it can use `dyn` to eliminate the warnings?

**Comment by stepancheg** [comment] 2019-07-10 17:03
@jakubadamw Maybe I'm missing something. Can you please show how to reproduce the problem?

**Comment by stepancheg** [comment] 2019-07-10 17:03
(At least show generated code)

**Comment by jakubadamw** [comment] 2019-07-10 18:04
@stepancheg https://github.com/jakubadamw/rust-protobuf-414

```
> cargo build
   Compiling reproduction_414 v0.0.1 (/home/jakub/protobuf_warnings)
warning: trait objects without an explicit `dyn` are deprecated
  --> src/example.rs:91:26
   |
91 |     fn as_any(&self) -> &::std::any::Any {
   |                          ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn (::std::any::Any)`
   |
   = note: #[warn(bare_trait_objects)] on by default

warning: trait objects without an explicit `dyn` are deprecated
  --> src/example.rs:92:18
   |
92 |         self as &::std::any::Any
   |                  ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn (::std::any::Any)`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/example.rs:94:38
   |
94 |     fn as_any_mut(&mut self) -> &mut ::std::any::Any {
   |                                      ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn (::std::any::Any)`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/example.rs:95:22
   |
95 |         self as &mut ::std::any::Any
   |                      ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn (::std::any::Any)`

warning: trait objects without an explicit `dyn` are deprecated
  --> src/example.rs:97:55
   |
97 |     fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
   |                                                       ^^^^^^^^^^^^^^^ help: use `dyn`: `dyn (::std::any::Any)`

    Finished dev [unoptimized + debuginfo] target(s) in 2.98s
```

**Comment by ilblackdragon** [comment] 2019-07-18 01:10
Same here for `warning: trait objects without an explicit `dyn` are deprecated` with 2.7 and Rust 1.37

**Comment by stepancheg** [comment] 2019-07-18 03:59
OK, I see, the problem exists in stable but does not exist in master.

I don't know how to fix in stable.

```
&dyn ::std::any::Any
```

This syntax is not valid in edition 2015. And edition 2018 is not available until Rust 1.32.0 (2019-01-17).

[Play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=50960221944349f7a30c05541a69edee)

So if you know how to fix it, please let me know.

Otherwise, there are two options:
* set minimum supported version 1.32 (it is 1.27 now)
* keep warning as is

Ideas?

**Comment by zsluedem** [comment] 2019-07-19 14:21
I am facing the problem, too.  
These warnings(I have 2000+warnings) would heavily trouble people debug.

I am quite new in rust.
How to set minimum supported version 1.32?

**Comment by bacek** [comment] 2019-07-22 20:24
I think bumping minimal supported version to 1.32 and switch edition should be fine.

Another options are:
1. to extend Customize object to explicitly enable `dyn Trait` generation.
2. Detect `edition` in protoc-rust and generate code for it.

**Comment by stepancheg** [comment] 2019-07-23 03:10
Let's set the minimum version to 1.32 since 2.8. Going to do it now.

**Comment by stepancheg** [comment] 2019-07-23 03:10
I'll do it now.

**Comment by stepancheg** [comment] 2019-07-23 03:19
OK, stupid me.

It's not enough. `&dyn Trait` cannot be used even in latest stable.

**Comment by stepancheg** [comment] 2019-07-23 03:41
Got another idea: https://github.com/stepancheg/rust-protobuf/commit/df9780f4bc4328dc23e29ece8dab20fc88b975b7

**Comment by stepancheg** [comment] 2019-07-23 04:15
Published 2.8.0. Please let me know if it doesn't solve the problem.

**Comment by bacek** [comment] 2019-07-23 06:45
Are you sure it's compatible with 2015 edition?

**Comment by bacek** [comment] 2019-07-23 06:46
Ah. 1.27. Should be all right.

**Comment by stepancheg** [comment] 2019-07-23 06:48
> Are you sure it's compatible with 2015 edition?

Yes, because the protobuf library and all tests are done against the 2015 edition.

I'm a bit worried about compatibility with 2018 edition. I did basic checks, but there are no automated CI tests.

**Comment by bacek** [comment] 2019-07-23 07:03
Works for me in my 2018 edition project.

**Comment by feuerste** [comment] 2019-07-23 07:26
Works for me, too, thanks! You may also add the 2.8.0 release in github?

**Comment by stepancheg** [comment] 2019-07-23 07:30
@feuerste I forgot to do `git push`. Thank you for the reminder!

**Closed** 2019-07-23 16:37 UTC
