### ISSUE TITLE
protoc_rust does not handle file path with backslashes properly on windows.

### ISSUE THREAD

**Issue by dvush** [stepancheg/rust-protobuf#356] opened 2018-12-13 15:56 UTC
Hi.

It seems that `protoc_rust` does not handle slashes in paths correctly.
If you pass valid path on windows(with "\") to `protoc_rust::run` it won't work.

example that does not work on windows https://github.com/dvush/protoc_path_buf.git

**Comment by stepancheg** [comment] 2018-12-19 04:39
I've set up travis-ci on Windows: https://travis-ci.org/stepancheg/rust-protobuf/builds/469847927

This is the first step.

Next steps are:

* fix the build
* reproduce and fix the issue you've reported

(You can send PR of course, but I cannot fix it myself without CI, I don't have a Windows box)

**Comment by stepancheg** [comment] 2018-12-19 20:22
OK, the problem is reproduced on Windows in CI: https://travis-ci.org/stepancheg/rust-protobuf/jobs/470187677 now need to fix it.

**Comment by stepancheg** [comment] 2018-12-29 03:11
Should be fixed now. Published v2.2.2. Please reopen if the problem still exists.

**Closed by stepancheg** 2018-12-29 03:11 UTC
