### ISSUE TITLE
parse_length_delimited_from_reader doesn't return with TcpStream on Windows

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [stepancheg/rust-protobuf#264] opened 2018-01-11 18:11 UTC

**Comment by stepancheg** [comment] 2018-01-11 18:21
Which version do you use? Similar issue #157 was fixed in 1.4.2.

**Comment by Supernerd11** [comment] 2018-01-11 18:37
1.4.3

**Comment by stepancheg** [comment] 2018-01-12 00:14
I can try to reproduce it myself, but if you could provide a minimal example which doesn't work properly, that would help.

**Comment by Supernerd11** [comment] 2018-01-12 13:41
well, my code is exactly:
```rust
fn main() {
  let mut sock = TcpStream::connect("127.0.0.1:50000").unwrap();

  let mut conn_req = ConnectionRequest::new();
  conn_req.set_client_name("rusty".to_string());
  conn_req.set_field_type(ConnectionRequest_Type::RPC);

  conn_req.write_length_delimited_to_writer(&mut sock).unwrap();

  // NOTE: this is my work-around.
  // let msg_len = read_varint(&mut sock).unwrap();
  // let mut buf : Vec<u8> = Vec::with_capacity(msg_len);
  // sock.read_exact(&mut buf).unwrap();
  // let resp : ConnectionResponse = protobuf::core::parse_from_bytes(&buf).unwrap();
  
  let resp : ConnectionResponse = protobuf::core::parse_length_delimited_from_reader(&mut sock).unwrap();

  let req = Request::new();
  let call = ProcedureCall::new();  

  println!("{:?}", resp);
}
```

I am trying to use a mod called kRPC for a game called Kerbal Space Program.
That is where the definitions came from.

**Comment by stepancheg** [comment] 2018-01-24 09:02
I've added a smoke test in be44b090b06e58d0d83227f1db233dae886767e2.

Unfortunately it doesn't revel anything at least on macOS.

I'll try to find a windows box and try to reproduce problem there.

And if you coud create a standalone reproducible example (e. g. basic cargo project with all dependencies) that woud be helpful.

BTW, you know for sure problem is Windows-specific or you didn't try running it on different OSes?

**Comment by Supernerd11** [comment] 2018-01-24 09:53
I haven't tried it on any other OS, no.

**Comment by slin31** [comment] 2018-02-04 14:21
I can confirm that this issue exists on other platforms as well. I'm using Linux and coincidentally I'm working with the same thing: the kRPC mod for Kerbal Space Program.
I worked around the problem by doing this
```rust
let answer: krpc::ConnectionRespone = core::parse_length_delimited_from(&mut CodedInputStream::new(&mut stream)).unwrap();
```
So everything seems to work fine if I explicitly use the CodedInputStream, but it is far more convenient to just pass in the TcpStream like I can for the writeing part of the connection.

The parse_length_delimited_from_reader function mention a TODO about reading the length of the message by the way: [link](https://github.com/stepancheg/rust-protobuf/blob/02fdf8a4f98ec6912a3916ee6293e68d21613966/protobuf/src/core.rs#L261)
Perhaps that's where the issue hides?

**Comment by stepancheg** [comment] 2022-02-08 01:43
Closing due to old age. Please reopen if it is still relevant.

**Closed by stepancheg** 2022-02-08 01:43 UTC
