### ISSUE TITLE
protobuf3 support

### ISSUE THREAD

**Issue by rryan** [stepancheg/rust-protobuf#76] opened 2015-03-07 03:32 UTC
- [x] Store scalar values without option, do not serialize zeros (implemented in master)
- [x] Maps
- [x] text format
- [x] `Any`

**Comment by stepancheg** [comment] 2015-03-07 03:45
No work has been done yet, but I'm planning to implement protobuf3.

However, I'm not in hurry, because protobuf3 specs are not published yet.

BTW, rust-protobuf still has no implementation of all protobuf 2.6 features, notably `one_of`.

**Comment by stepancheg** [comment] 2015-03-15 02:00
Added test with protoc from protobuf 3: cabca6d5bf2d8129f26f957c53ab8a34939c5692.

I believe that `.proto` files with `syntax=3` should work in rust-protobuf. I'll add test for that later.

However, new features of protobuf 3 need to be implemented. If some features are important, please let me know.

**Comment by posix4e** [comment] 2016-05-30 06:21
Is this still the case?

**Comment by stepancheg** [comment] 2016-05-30 13:54
Protobuf3 works correctly, but could be done better. E. g. protobuf 3 mandates that there is no field presence flag in the message, while generated code still contains functions like `has_foo()`.

**Comment by posix4e** [comment] 2016-05-31 02:30
Should we close this issue and create a new more specific one then?

**Comment by stepancheg** [comment] 2016-06-07 01:22
@posix4e well, the largest problem is that I don't fully understand what generated code for protobuf 3 should look like, and what could be done better in protobuf 3. For example, given the fact that there is no presence bit for primitive types in proto3, should generated messages contain `get_foo`, `set_foo` operations or just expose public `foo` field?

Another question is whether rust-protobuf should remain compatible with protobuf 2 protoc compiler. If the answer is yes, then for example rust-protobuf cannot include "well-known types" like `Timestamp`. And I think at this point compatibility with protobuf 2 protoc is important.

(However, rust-protobuf should probably use `descriptor.proto` from protobuf 3, which uses `proto2` syntax).

So if you (anyone else) know what should be done for better protobuf3 support, please open an issue.

**Comment by mfirry** [comment] 2016-09-16 09:26
Any news on this? We wanted to start a new project using proto3 and rust was one of the platform we wanted to try.

**Comment by stepancheg** [comment] 2016-09-16 17:53
@mfirry you can use it with protobuf 3 proto files, and it will be compatible with other readers and writers. Minor issues to be resolved are:

* zeros are serialized, while it is not necessary in protobuf 3, because protobuf 3 does not distinguish zero value and no value. Again it does not make rust-protobuf incompatible with protobuf 3, but rather adds little overhead.
* maps are not supported
* generated code does not need `has_xxx` functions because they are meaningless in protobuf 3

**Comment by mfirry** [comment] 2016-09-19 20:14
Thanks a lot! I'll try it out.

**Comment by opensrcken** [comment] 2016-09-19 20:26
> maps are not supported

When will this library add support for maps?

**Comment by stepancheg** [comment] 2016-09-19 23:30
@opensrcken I'm working on it.

However, you can use map right now, but rust-protobuf will generate a repeated field of some struct instead of map (this is what maps internally are in protobuf).

**Comment by stepancheg** [comment] 2016-09-19 23:33
Quoting protobuf language guide:

> Backwards compatibility
> 
> The map syntax is equivalent to the following on the wire, so protocol buffers implementations that do not support maps can still handle your data:
> 
> ```
> message MapFieldEntry {
>   key_type key = 1;
>   value_type value = 2;
> }
> 
> repeated MapFieldEntry map_field = N;
> ```

**Comment by stepancheg** [comment] 2016-09-20 01:33
FYI, zeros are no longer written and has methods removed in master.

**Comment by stepancheg** [comment] 2016-09-24 03:45
Maps are (mostly) implemented in master.

Generated code for map looks [like this](https://gist.github.com/stepancheg/f2017806985d5df62ac737c3bb2f5c29). Note, information about actual type name used for entry is lost in generated files (it is generated by protoc and passed to the compiler). I'm not sure why they kept it in java and c++ versions of protobuf.

I made primitive scalar fields (`i32`, `String`) public in generated code from protobuf 3 definition ([example](https://gist.github.com/stepancheg/27379bca3b510df94e001e7d35bb11d3)), but other fields remain private. Not sure if map (or probably any repeated fields even for protobuf 2) should be public too.

If you have opinions about what code should be generated by rust-protobuf, please share. It is not too late to change everything before rust-protobuf with protobuf 3 support released. It should probably be source-incompatible release (in both library and generated code), but rust-protobuf should remain backward compatible after next release.

**Comment by aajtodd** [comment] 2016-11-12 00:35
Curious what the status is of this right now. Is Any support complete? Thanks!

**Comment by martinmroz** [comment] 2017-02-24 23:59
The removal of Option<> does make things interesting from an API usability perspective. In many cases, when de-serializing, I want to know whether something is 0 or None (for instance, I have a truly optional Altitude integer field, for which there is a semantic difference between 0ft and 'I don't know'/'Not Set'). Should that be represented with my own Proto equivalent to Option<T>? Thanks for your work on this!

**Comment by stepancheg** [comment] 2017-02-25 22:11
@martinmroz it is by design in protobuf v3. They decided not to distinguish default values from absent values. Quoting [the documentation](https://developers.google.com/protocol-buffers/docs/proto3):

> Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all: you should bear this in mind when defining your message types. For example, don't have a boolean that switches on some behaviour when set to false if you don't want that behaviour to also happen by default. Also note that if a scalar message field is set to its default, the value will not be serialized on the wire. 

Although it is possible to distinguish between these cases, I think it is better to follow protobuf recommendation (for example, for better interoperability with C++/Java/Go/Python implementations).

BTW, you can specify `syntax = proto2` and get old behavior. Protobuf 2 is supported, and seems like it is not going to be deprecated any time soon.

**Comment by stepancheg** [comment] 2017-04-23 20:36
Added support for well-known types in 653f8548f1817688c8816686728ce312d3f99168.

**Closed** 2017-04-23 20:36 UTC
