### ISSUE TITLE
Disabling accessor generation causes has_* errors

### ISSUE THREAD

**Issue by spease** [stepancheg/rust-protobuf#478] opened 2020-04-03 09:13 UTC
I was trying to use expose_fields and disable accessors. However, when I disable accessors, there's some reflection that attempts to use the has_ fields, which causes a compile-time error. Unfortunately, I don't have a good example right now as the protobufs I'm working with are proprietary. I'm hoping this is probably obvious what I'm talking about.

Thanks.

**Comment by stepancheg** [comment] 2022-02-08 01:54
Closing due to old age.

If the issue still exists, please reopen.

Also, PR is welcome, even reproducing the issue.

**Closed by stepancheg** 2022-02-08 01:54 UTC
